# Generated by Django 3.1.6 on 2021-10-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Автор'),
        ),
    ]
